
---

## 🤖 GitHub Actions: `.github/workflows/ci.yml`

```yaml
name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install build tools
        run: sudo apt-get install cmake g++ libgl1-mesa-dev
      - name: Configure
        run: cmake -S . -B build
      - name: Build
        run: cmake --build build
